version: '3'

services:
    mysql:
        image: mysql/mysql-server
        ports:
            - "127.0.0.1:3306:3306"
        expose:
            - "3306"
    forex:
        build: .
        depends_on:
            - mysql
        ports:
            - "127.0.0.1:3000:3000"
        expose:
            - "3000"
        links:
            - mysql