version: '2'

services:
    mysql:
        image: mysql/mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            -   type: bind
                source: ./docker_db
                target: /docker-entrypoint-initdb.d
        expose:
            - "3306"
        networks:
            - app-network
    forex:
        build:
            context: .
            dockerfile: Dockerfile
        command: npm start
        depends_on:
            - mysql
        ports:
            - "127.0.0.1:3000:3000"
        expose:
            - "3000"
        links:
            - mysql
        networks:
            - app-network